function [] = task1( dataset_path )
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here

    dataset_path = strcat(dataset_path, 'dataset/');
    
    INTERVALS = 5;
    ADAPTATIVE = true;
    OPT = 'ALPHA_SEARCH';
    COLOR = false;
    FILLING = true;
    
    % HIGHWAY SEQUENCE EXPERIMENT
    RHO_HIGHWAY = 0.25;
    HIGHWAY_SEQ = [1050, 1350];
    HIGHWAY_PATH = strcat(dataset_path, 'baseline/highway/');
    disp('##### HIGHWAY SEQUENCE EXPERIMENT 4 CONNECTIVITY FILLING #####')
    bg_experiment(HIGHWAY_SEQ, HIGHWAY_PATH, 'HIGHWAY', INTERVALS, 0, RHO_HIGHWAY, ADAPTATIVE, OPT, COLOR, 4, FILLING);
    disp('##### HIGHWAY SEQUENCE EXPERIMENT 8 CONNECTIVITY FILLING #####')
    bg_experiment(HIGHWAY_SEQ, HIGHWAY_PATH, 'HIGHWAY', INTERVALS, 0, RHO_HIGHWAY, ADAPTATIVE, OPT, COLOR, 8, FILLING);
    disp('##### HIGHWAY SEQUENCE EXPERIMENT NO CONNECTIVITY FILLING #####')
    bg_experiment(HIGHWAY_SEQ, HIGHWAY_PATH, 'HIGHWAY', INTERVALS, 0, RHO_HIGHWAY, ADAPTATIVE, OPT, COLOR, 0, false);
    
    % FALL SEQUENCE EXPERIMENT
%     RHO_FALL = 0.052632;
%     FALL_SEQ = [1460, 1560];
%     FALL_PATH = strcat(dataset_path, 'dynamicBackground/fall/');
%     disp('##### FALL SEQUENCE EXPERIMENT 4 CONNECTIVITY FILLING #####')
%     bg_experiment(FALL_SEQ, FALL_PATH, 'FALL', INTERVALS, 0, RHO_FALL, ADAPTATIVE, OPT, COLOR, 4, FILLING);
%     disp('##### FALL SEQUENCE EXPERIMENT 8 CONNECTIVITY FILLING #####')
%     bg_experiment(FALL_SEQ, FALL_PATH, 'FALL', INTERVALS, 0, RHO_FALL, ADAPTATIVE, OPT, COLOR, 8, FILLING);
%     disp('##### FALL SEQUENCE EXPERIMENT NO CONNECTIVITY FILLING #####')
%     bg_experiment(FALL_SEQ, FALL_PATH, 'FALL', INTERVALS, 0, RHO_FALL, ADAPTATIVE, OPT, COLOR, 0, false);



    % TRAFFIC SEQUENCE EXPERIMENT
%      RHO_TRAFFIC = 0.157895;
%     TRAFFIC_SEQ = [950, 1050];
%     TRAFFIC_PATH = strcat(dataset_path, 'cameraJitter/traffic/');
%     disp('##### TRAFFIC SEQUENCE EXPERIMENT 4 CONNECTIVITY FILLING #####')
%     bg_experiment(TRAFFIC_SEQ, TRAFFIC_PATH, 'TRAFFIC', INTERVALS, 0, RHO_TRAFFIC, ADAPTATIVE, OPT, COLOR, 4, FILLING);
%     disp('##### TRAFFIC SEQUENCE EXPERIMENT 8 CONNECTIVITY FILLING #####')
%     bg_experiment(TRAFFIC_SEQ, TRAFFIC_PATH, 'TRAFFIC', INTERVALS, 0, RHO_TRAFFIC, ADAPTATIVE, OPT, COLOR, 8, FILLING);
%     disp('##### TRAFFIC SEQUENCE EXPERIMENT NO CONNECTIVITY FILLING #####')
%     bg_experiment(TRAFFIC_SEQ, TRAFFIC_PATH, 'TRAFFIC', INTERVALS, 0, RHO_TRAFFIC, ADAPTATIVE, OPT, COLOR, 0, false);
end

